### ISSUE TITLE
readme outdated?

### ISSUE THREAD

**Issue by drewswaycool** [tomhammond/bing_ads_api_v9#1]
Is this readme up to date or a copy from https://github.com/arambert/bing_ads_api?

i.e. your readme says to, use 

gem 'bing_ads_api', :git => 'https://github.com/arambert/bing_ads_api.git'

instead of 

gem 'bing_ads_api_v9'

**Comment by tomhammond** [comment]
It was a copy :) - I pulled from his version (which handles the api v7/8) to create this one to support v9.

Should be updated now though!

**Comment by drewswaycool** [comment]
Cool, however running a bundle install with your updated:

gem 'bing_ads_api', :git => 'https://github.com/tomhammond/bing_ads_api_v9'

returns "Could not find gem 'bing_ads_api (>= 0) ruby' in https://github.com/tomhammond/bing_ads_api_v9 (at master).
Source does not contain any versions of 'bing_ads_api (>= 0) ruby'"

did you mean to change it to:

gem 'bing_ads_api_v9', :git => 'https://github.com/tomhammond/bing_ads_api_v9'?
